### ISSUE TITLE
crash in HPSEstimator.estimateLocation due to wrong range values

### ISSUE THREAD

**Issue by glaurent** [vadymmarkov/Beethoven#29]
Having updated to the current master, I seem to now often encounter a problem in HPSEstimator.estimateLocation. The following line

``` swift
for i in (minIndex + 1)..<maxsearch {
      if spectrum[i] > spectrum[max2] {
      ...
```

crashes because minIndex = 20 (at least in both cases I had that crash) and maxsearch is <20 (15 or 17).

**Comment by vadymmarkov** [comment]
Fixed by https://github.com/vadymmarkov/Beethoven/pull/32
