### ISSUE TITLE
crash if InputSignalTracker.stop() is called twice

### ISSUE THREAD

**Issue by glaurent** [vadymmarkov/Beethoven#31]
public func stop() {
    audioEngine.stop()
    audioEngine.reset()
    audioEngine = nil
    captureSession.stopRunning()
  }

on 2nd call, audioEngine.stop() will crash since audioEngine is nil.

**Comment by vadymmarkov** [comment]
Fixed by https://github.com/vadymmarkov/Beethoven/pull/32
