### ISSUE TITLE
Example throws exception

### ISSUE THREAD

**Issue by matheusjkweber** [vadymmarkov/Beethoven#41]
Hi, I am trying to test the guitarTurner, but captureSession.startRunning() is throwing a exception.

I am on Xcode8.

![screen shot 2016-10-26 at 3 09 40 pm](https://cloud.githubusercontent.com/assets/15331222/19736491/441a50d0-9b8e-11e6-80cf-66c03380b45b.png)

**Comment by vadymmarkov** [comment]
@matheusjkweber Hm..interesting. Are you testing on device?

**Comment by maththedev42** [comment]
Hi @vadymmarkov, I was testing on simulator, in Ipad/iPhone works fine, sorry to bother you :)
