### ISSUE TITLE
Update for Swift 3.1?

### ISSUE THREAD

**Issue by PCrompton** [vadymmarkov/Beethoven#47]
Hi @vadymmarkov, It's been a while since I've tried to compile my app that depends on this framework, and I'm getting an error when I try to import Pitchy: "Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1" 

![screen shot 2017-06-20 at 2 31 24 pm](https://user-images.githubusercontent.com/2374809/27349462-4fee5cfc-55c5-11e7-8737-5ccaaa587f1d.png)

I also tried updating Beethoven with Carthage and got the following error:

```
carthage update beethoven
*** Fetching Beethoven
*** Fetching Pitchy
*** Fetching Quick
*** Fetching Nimble
*** Checking out Nimble at "v5.1.1"
*** Checking out Quick at "v1.0.0"
*** Checking out Pitchy at "2.0.1"
*** Checking out Beethoven at "3.0.1"
*** xcodebuild output can be found in /var/folders/bm/25m_zbpn1ys21pt5xc004p6h0000gp/T/carthage-xcodebuild.PYOJL6.log
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Nimble-tvOS" in Nimble.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

I'm running Xcode 8.3.3

Any change you could compile and rerelease for Swift 3.1?

Thanks!

-Paul

**Comment by PCrompton** [comment]
Just a follow up, I switched from Carthage to CocoaPods and it worked, because CocoaPods builds the framework locally from the source code, whereas Carthage doesn't. So I suggest either updating for Carthage or removing Carthage instructions from the Readme.

**Comment by vadymmarkov** [comment]
Swift 4 version is released, so I don't think it's relevant anymore. But you should be able to use both CocoaPods and Carthage to install the framework though.
