### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mobyIsMe** [vadymmarkov/Beethoven#58]
hi, I have got sevaral compile errors ,please help me.
![image](https://user-images.githubusercontent.com/9191594/37859919-9514cd5a-2f56-11e8-981d-e7bee546b1db.png)
![image](https://user-images.githubusercontent.com/9191594/37859921-9ca2dc42-2f56-11e8-83e2-7dc86e73a93b.png)
![image](https://user-images.githubusercontent.com/9191594/37859926-a94d330c-2f56-11e8-9267-b4d7e7807c72.png)
![image](https://user-images.githubusercontent.com/9191594/37859932-b1f83b50-2f56-11e8-9d33-4f735e645629.png)

**Comment by vadymmarkov** [comment]
@mobyIsMe What version of Swift are you on?

**Comment by mobyIsMe** [comment]
xcode9，swift3

**Comment by vadymmarkov** [comment]
Then it's probably because the last version of the framework is in Swift 4. Use v3.0.1 if you need it in Swift 3 project.
