### ISSUE TITLE
But beethoven is deaf

### ISSUE THREAD

**Issue by logg926** [vadymmarkov/Beethoven#64]
Beethoven is deaf

**Comment by OfTheWolf** [comment]
Is this a bug or feature request? :D

**Comment by harooniqbal1993** [comment]
It does not start often, I have to start it twice. I am using AVPlayer, AudioKit player (AKPlayer). Moreover, I want start on button click, But I have to start it in ViewDidLoad() to make it start.  Code is below

if pitchEngine.active {
      print("started ")
  }
  else {
      pitchEngine.start()
      pitchEngine.start()
  }

**Comment by logg926** [comment]
You should start a new issue if it is an issue
