### ISSUE TITLE
Podfile incorrect swift version set?

### ISSUE THREAD

**Issue by stekyne** [vadymmarkov/Beethoven#69]
Hi, I'm trying to use this library with Swift 5 but it's giving me an error saying it's at Swift Version 3.0.

The podspec file has it set here:
https://github.com/vadymmarkov/Beethoven/blob/774fe12b412d1e0c29e75d45ca5b0b5429b01495/Beethoven.podspec#L22

Is that right?

**Comment by alcalyx** [comment]
Yeah, i encounter same issue, i cannot build after do `pod install`
